	git add   adm/route_adm_settings.php
	git add   adm/route_adm_users.php
	git add   adm/settingsdelete.class.php
	git add   adm/settingsget.class.php
	git add   adm/settingsgetall.class.php
	git add   adm/settingshelper.class.php
	git add   adm/settingspost.class.php
	git add   adm/usersdelete.class.php
	git add   adm/usersget.class.php
	git add   adm/usersgetall.class.php
	git add   adm/usershelper.class.php
	git add   adm/userspost.class.php
	git add   cc/actiondelete.class.php
	git add   cc/actionget.class.php
	git add   cc/actiongetall.class.php
	git add   cc/actionhelper.class.php
	git add   cc/actionpost.class.php
	git add   cc/baltransferinfodelete.class.php
	git add   cc/baltransferinfoget.class.php
	git add   cc/baltransferinfogetall.class.php
	git add   cc/baltransferinfohelper.class.php
	git add   cc/baltransferinfopost.class.php
	git add   cc/cardsdelete.class.php
	git add   cc/cardsget.class.php
	git add   cc/cardsgetall.class.php
	git add   cc/cardshelper.class.php
	git add   cc/cardspost.class.php
	git add   cc/companydelete.class.php
	git add   cc/companyget.class.php
	git add   cc/companygetall.class.php
	git add   cc/companyhelper.class.php
	git add   cc/companypost.class.php
	git add   cc/route_cc_action.php
	git add   cc/route_cc_baltransferinfo.php
	git add   cc/route_cc_cards.php
	git add   cc/route_cc_company.php
	git add   cc/route_cc_transaction.php
	git add   cc/transactiondelete.class.php
	git add   cc/transactionget.class.php
	git add   cc/transactiongetall.class.php
	git add   cc/transactionhelper.class.php
	git add   cc/transactionpost.class.php
	git add   client/addressdelete.class.php
	git add   client/addressget.class.php
	git add   client/addressgetall.class.php
	git add   client/addresshelper.class.php
	git add   client/addresspost.class.php
	git add   client/businessdelete.class.php
	git add   client/businessget.class.php
	git add   client/businessgetall.class.php
	git add   client/businesshelper.class.php
	git add   client/businesspost.class.php
	git add   client/ccdelete.class.php
	git add   client/ccget.class.php
	git add   client/ccgetall.class.php
	git add   client/cchelper.class.php
	git add   client/cchistorydelete.class.php
	git add   client/cchistoryget.class.php
	git add   client/cchistorygetall.class.php
	git add   client/cchistoryhelper.class.php
	git add   client/cchistorypost.class.php
	git add   client/ccpost.class.php
	git add   client/financialsdelete.class.php
	git add   client/financialsget.class.php
	git add   client/financialsgetall.class.php
	git add   client/financialshelper.class.php
	git add   client/financialspost.class.php
	git add   client/persondelete.class.php
	git add   client/personget.class.php
	git add   client/persongetall.class.php
	git add   client/personhelper.class.php
	git add   client/personpost.class.php
	git add   client/route_client_address.php
	git add   client/route_client_business.php
	git add   client/route_client_cc.php
	git add   client/route_client_cchistory.php
	git add   client/route_client_financials.php
	git add   client/route_client_person.php
	git add  db/scripts/ccpoints_create_schema.sql
	git add  db/scripts/f_angular_class_create.sql
	git add  src/adm/usersget.class.php
	git add  src/adm/usersgetall.class.php
	git add  src/adm/usershelper.class.php
	git add  src/adm/userspost.class.php
	git add  src/routes.php
	git add  	db/scripts/adm_users.json
	git add  	db/scripts/f_angular_form_create.sql
	git add  	db/scripts/f_angular_service_create.sql
	git add  	db/scripts/sp_angular_class_create.sql
	git add  	db/scripts/sp_angular_service_create.sql
	git add  	src/adm/userslogin.class.php
	git add  	src/meta/angularcreateclass.class.php
	git add  	src/meta/angularcreateform.class.php
	git add  	src/meta/angularservicecreate.class.php

